# Generated by Django 5.2.9 on 2025-12-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_options_course_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name_plural': 'User Progress'},
        ),
    ]
