# Generated by Django 5.2.9 on 2025-12-13 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_coursereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Video subido desde tu PC (MP4, WebM, OGG, MOV, AVI)', null=True, upload_to='course_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov', 'avi'])]),
        ),
    ]
